TEXT_TEAM = ['Easy', 'Medium', 'Hard']

TEXT_GAMEOVER = 'YOU RAN OUT OF BALLS'
TEXT_SCORE = 'FINAL SCORE : '
TEXT_PAUSE = 'PAUSE'
TEXT_PANEL = 'Congratulations!!\nYou scored '
TEXT_PANEL_POINT = ' Runs.'
TEXT_REDEEM = ' Target was '
TEXT_BOWLED = 'MISSED!'
SCORE_TEXT = 'SCORE: '
TARGET_TEXT = 'TARGET: '
TEXT_START = 'START'
TEXT_CREDITS_DEVELOPED = ''
TEXT_SELECT_YOUR_TEAM = 'SELECT LEVEL'
TEXT_LINK = ''
TEXT_HIT = 'HIT'
TEXT_ARE_SURE = 'ARE YOU SURE?'
//TEXT_CONGRATULATION = ["GOOD!", "GREAT!", "EXCELLENT!!!"];
TEXT_CONGRATULATION = ['2 RUNS!', '4 RUNS!', '6 RUNS!!', '1 RUN']
TEXT_LOADING = 'LOADING'
TEXT_SELECT_MODE = 'SELECT MODE'
TEXT_BATTER = 'BATSMAN'
TEXT_BOWLER = 'BOWLER'
TEXT_HOW_TO_PLAY = 'HOW TO PLAY'
TEXT_HELP1_PC_BATTER =
	'PRESS THE CORRESPONDING KEY WHEN THE BALL TARGET BECOMES GREEN'
TEXT_HELP1_MOBILE_BATTER =
	'TOUCH THE CORRESPONDING ARROW WHEN THE BALL TARGET BECOMES GREEN'

TEXT_SHARE_IMAGE = '200x200.jpg'
TEXT_SHARE_TITLE = 'Congratulations!'
TEXT_SHARE_MSG1 = 'You collected <strong>'
TEXT_SHARE_MSG2 = ' points</strong>!<br><br>Share your score with your friends!'
TEXT_SHARE_SHARE1 = 'My score is '
TEXT_SHARE_SHARE2 = ' points! Can you do better?'
